---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-telegram
  namespace: monitoring
spec:
  encryptedData:
    botToken: AgCZ3hsUawt7MnxfYEYSY99RMmeiNV6FxoB8vesSxLfAb1AkTAZp4Xf+ZIxEstXfmlnhVShi5Ff8aYmuYUa7Hy4RL2uz38opKeN+bLBDP4uYeXLn5K+XZG7kYr4nhOvfYXAI55e8HXTK+ocnYTi+c8jVQXeRo/IiyV56OhLv2dfLstEMzZQyRYbqjbEc2T1qBoKg+oZu0mBwg4DI22qN9kmullDsyXEmNjOY9c0XG2kMwwa0l76hO/mjpuTRocKkyTeG60FccHQmStlUxB1aDgaRKeI++QQkMMiHvBniuZHxJiPL6p6bdt9amwHv8Tm+RD5h0Hd6sVas1scqFRdMhXJaeNX44ErY+RU1tMAjRF+a26gDELZSe761ja5WZM0CRlmvyultBCV9QgIrTmXDXDsZ7FDh6AeZVgyzDY8TXFbwhXRRPMRLem1WcD192IvSq7DGk7WSsQDnH8iqN62YvvklCXGiVb2yG9tqGCeYFn/aGrWczgEsM84i2qEoG2zElknXYZ3FWxOYueI0w7+iET2DkI2wtuH9S50HRdJ+2ye9zogtObvthQ8tnpcTybrogyULceCdCPT70ADICuKvx5ExWOAUt3eLnOHbdBvIizHrrHKNxeIrrvbbYcCsHYEI8Sz3oE63NQ+HTfeztC4rCAj9UuLRx5moVb1vsmt+Z2NXR03+ykoJZKD3ujXFk0h4Ihzvs91mNcXJ8h8UOHIkdeEiEos8UG8ONPv1Ms0wlbSXCT8z8Bu2TZQPwG9v/9W6
    chatId: AgAx/gWmacAOceh+vr63IsPGYiNDEbNe1Q6r9KpJBaQ4JoI/9trWBPnYbOS+RzpvVEL056In7uE5N4evS2BvqY4w361tbie8jI0vXnjc1OlJ66D+b+nn5Ar5VgpkkU7vWz8sSXWjX01Z4INrH3nVBuwagc5oyCNO+P4bWJC/wtQYx/X9MToRA1EcbuNcQQFVB6Yd1Fv2JQ7c2Z7uGgq/ISHwon/iH+EVsvYI61kL0GHvG8FM4sa722xn8b11GUak7y3RlkKyF55+IF68KJq30AhTtXuo02ghCwEnrVGdTGqHQcnjFUIalRTLRw/dqIfTngM8nnG1r9SUJrLgIDXL7QSKejEkQuEdT1kZEBh2GnY/A74mBt2EZk91xkJZXhz7yWnUHBrWxsJJAY8UKlwxmEBvI1JP2UmA7PPo81GHHChASPK0DqBGPI3exZjdbuJDwPmmF5YLIASt8ud6aspYdyD9x6/2SBB1efdBLrPW1ei71HBYtM7wICXefsFTQDiE00YyahRLYg7LZZklYnPOr9sGC3RBuaDLdS9UOc+k3ln/muGy54QGlnkIwQI6oqdA36TF56qDfd32Db2bcJlhRMXMF5qEemVxe3klm4dXJN+lkiRV50Ky0nWE1k26B06sIRCMzVMFhfUA2JUiKktnQ4tA1Mzr/rinoavIsRTA65DilVwPGjzOAY5LYNkAkYDtp5XytzURqL+lLBRH
  template:
    metadata:
      name: alertmanager-telegram
      namespace: monitoring
