---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-auth
  namespace: redis
spec:
  encryptedData:
    redis-password: AgBYii/q9nCClgg5JoM+PLaUVzro5ZAjFK4mcSZgA4rnvq4BIvDo14EUQjOtCKBxIRPgqfG7JMIYnM1dWf8LToDt0an+nrZT5B/+f0pR4l9kMM8C8Xbd1KomAlaNOTtkJ+wZ6kqlsvZcMrKkhbWWkzprb08O4ahyTRNxR5N94GOZPPqjeyBQVS/rwVDn7mPBZML6tLYH1iYqqx/RBknJ36Zo5pSsrSyUs97JdumCjXTp31/b/8uC4dDz0ktWwEqAABGt+18puDsboVBgv3SFxBwuF8/YqdybIeZO3UUrQo2vwzapLDx2TY+19+0L3OXXWmzKrGHr92mvaDPp1zVtA1ZofwF19G+SpYGvCuQDvwFPeN9RuFyWxLiCOcPhakGzuIzKEZgqbv0Fbc6RZamfYg4bLnY/Dza2qtOs8caPeGQUhCRWDkVBjvNRqR6qL3QY5fBlBjaLoZOnePThPFIlUubAwge/FiPn+dut7ReB7TLwUm7Fo+nUP4qrOhffTxuBDYrH+OMmvWsT7GhbpeWZtQeh5mI+n+/+eq1GEURloFjayAfGbVxXa6qKZpgswRl8tXesMdxCAw09xnGYwdmRvfEmyc6q+YnJosV4FLzMlPObU3ywAF6o0UNxNtzYR/HVW0MIhn3VPw2VMKxMptNosDVUi948Nu1MHrm3Z/CpdhrCqFhQWtoMtGFQ0C7yzOG+aK+kAGmlmP2ruMMxwCatNbAMar0a80ggYICeV+beWjDq3g==
  template:
    metadata:
      name: redis-auth
      namespace: redis
