---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: jenkins-admin
  namespace: jenkins
spec:
  encryptedData:
    jenkins-admin-password: AgAVcCSLZt8gcISa13ulDxPUM66mfTm++afvFd8GquhvuRhNcwkLgYhbxRplKuk/AqpcHaw/+OpIvHqGvEARn0dLZ2Oavyk02h4wf57111BxxSo+iFskcs9RienhPu4+FdZVrtkcTafCcwRqsyfTPtWAn00oBtHn8xqcIrpIWtjjIw/MMGr8LYS5ynJDb0jwsBjBy/z62kCsQFbx+DE9L4neYj1RLVXF5OOIwmVwsAFompb/9ky2EqcJKJ9x0GuavKxLRCjsb1pqvmwiXIf9c6FCfC2H9lleu+kDfuexA9GPlud7+DkVCTsyj8xZiEKyrByLYp2QC9qTb4VU/oc6dWFU+CgN0tnSRm70G5jOFeEU9TxhdKBBP5HYlhauUm8XNfi2RCwbN5rkmgg2AieuSkqqsHOZgyxkmiALDy+swjR1kQQ7YbDvNZKR7/hSRSzB2YXPyL0AaU5zf2RvCakMN2DU2HGqnvUqiZjKvQ3NXM6QQwXWycTqDNKaElzwdEkCDlEOhy8cHxAAWzuJx+kwwslwX6EzV29FI/dnxJn4qrmBjjW55Xxwi5Fu+d5bZFtfWrsklqJrDq9iPTFr8pc2Nbl/PCGhrOite16FHcQYSYjugxRG1HlUnC9tNMHwppviKA8Wy2eCpHcBsDsOumNrd7LNkJx9Ey9fWcAT83jnvqtuPXvLnlsSL7UiOxMoEjx6Ma7Sz69oGPvtu/vdpjEtylazs4M7DoUBQhsDQxm+zEvgKw==
    jenkins-admin-user: AgB9nGW0jjB0cLBCChVcE8sQnL/KTbrvg+/n4LbuHCNcmC0PkTfCBUl9YOSV2EurgBV7S488nL1E6yHXqQr37naWOXWbHrMCB6+z2/KmVMx34LkMVfluLzg+guX4bf7krsqGt8yoi6SD/Iynqw2IW28PylAK8ZwSwnFH1w5OYjvFu3U7l+/8V/wUJG02EPaR7Xu6RoQGSArXxxZFskQDbvGzcVWop9aio+K3R+hrg0xlzq8qFVb2nblGryIjnq1T+DUsQx6biPBtjnurfU3ZjQ1ZOMWi2C7/j1r7DVKZUjB7OHWU6fm1IMZYMxYcwuyA+NDEkIoXDIKBorijpHBOzQoDI7VTV2+hJ6y94hXNZH/n2D50b6PmVrrB8ISSHU8oJ2tG41d9JBuQIQsheeHRkBBWc4yLBeZOAj67F6aQcuoFdM9ReANQgepy64IQGrFqN1oLpxv27mgJvlZ6rgHOSfiRNqETvgRXIoWYohAeCw1nAPMKsk5SDbdGcARcjptU/BD4Q0+fRz4b7e4PcviR1blAbkWXSncBOrOMnarSyZKHWLdE0/aERJJylcbs1uydNgy4EaGXLA7bhrJt9F05Quu5UbLwMPf2MEFV7mMgrkke1tR+GAino3QVFk8jLS52mKigHQxJMnuspoXGliCxHZTrUYAYjChSFxeA4++rVFzYvyTPLloiFDkIbjAMm6Po+agMmzjvxg==
  template:
    metadata:
      name: jenkins-admin
      namespace: jenkins
