---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-push-token
  namespace: jenkins
spec:
  encryptedData:
    password: AgAvqD+RMkFxQA6BuWj0F50Ao70HEQ82rOvs0wrqts9EV9RGlWod8G5wBf7PVtxV6LxXEgI9Gpp7RzB2BjETRIEuoHk5XR7WQg+C83hmx5+Jt90Ur5dSEQKTHKFy3R9ilC5M/RW8nJq2XoIhqaGeHBHSEKNJoU6DFcxFPu1zi0CM9vD7Z4fAAeLbMIX+mKG7viVkuljNntdWtd4u/u882Oq/uDyYZM/0/YIZY9kj9PPika7OghcJqjioyoOm+qWjCRnBr8EZm1vyS5jrINVWz5uPJ9MIF5BKbvp4HE/VIYFntcQvmdN9i5a+k/KI3J2tCYT5p4KDpeoBUo6vJvENoDwkxL7hAvSszChD4Sw14uHzHZurTDH1s8zvJWtABsJpv/1N/PJJq9+oUrrC2bNwbv/Fg0ks/0lX0RTUAw7x0Ib4uM+pB6jlaShmx22nUDhdIcYMDGM4lhTqGCPdsEfaWfTtIPmxICLo+COwiiib2KX0g8OTZMVTBA8w66hbAecGBa4b7kR8mmRvPh8G6RraawO1hFbf2NkR5UCQebZsVlCnrP+SQ/eDCVTqRDPk1kW6RWVtYkLZrQiOexDz25qBosvCecHVNpwgRvssJhEVYljpqtFGeju602WCe24lLW6mJ2vVB/w8HlFpL+H4J8ed+HQDIDYtm8Bkg8JvwmyrLUsMyLaSbksR8JkyJMYI1er07u9Z9iX6cUnSgqI0FhTmOkZDAiqG0XsVu5Ahdese8suOOZ+iLaBQSETB
    username: AgA3a3VzigsRTb0Atvg+HYk4Zoq/OFSj7t5y/GIRkUkdzzFCiqijDC+TdloFShjAmR1zZ9jdUMhaSqT7a7TY5iEMTN2Q90xXwn5haxEeKkoBRbCWcen3tCXHeWGiJ9oJdwU5mxFfE9NnefFXOw5nC816HNwcb0hAVPMrZIcpAlerusn21hAPvEegMLvQzNxp5G3Dlflq/fC8Kt9Ghb+tUNN6k0M+FJClKKkBcsdeIO71PdTKHOt53v6xuunLKtVWFlk0Yg/fv+X6ZW0FyDG6kL51KexDo0wN+SnnEJDAU0rDzEhoi0914/qcy/p9lgZ0BlrQbO4B1QruENtcI1VR7UZhQlZIY1BopNkkGaO2bEf0q00dJQWw0xkURkcPmyUyf9JmIyBjy0fHN6FyeePRNPy6+RTrKYDD4nTeX0AuGs81FYIrgtSOq7bhaxuQn0NY0WR3+YssoPI9zrfUb4kNSndNIUO24YfpsQ82sangz6AecXXYdyhCAqMdW5SGUp/Fs/KYtrfKWkfoH1SkaTK7dgjF9dkNXKH8J+A5/+hYvAT8vURM+bZrVQEcnAqUmTXFwMyPvKxfur4BxY/aCBe3OOPLlINGJ010FcWxl6ngLSduPWgBeT/Wpby+8bUkYAWRNFecJZpf9njftZinnJbcJ5NingROPrfMiaa0O/qexqkb6IQ8+cIjOxZrz/g4vwVs5Nfqu0zyKwy+
  template:
    metadata:
      annotations:
        jenkins.io/credentials-description: ghcr.io push token for proxmox-iac-landing
          (PX-017, packages-only scope)
      labels:
        jenkins.io/credentials-type: usernamePassword
      name: ghcr-push-token
      namespace: jenkins
