---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-push-token
  namespace: jenkins
spec:
  encryptedData:
    password: AgB4Kg/p4fOMdtFDhdgkI2GkmmHdkaBdlD2FC2EKREguMZ5UTtIIV6h1lbMO+kZDIwhdXmL48/taqHI0ok+yLbV9Vgn9LzwVjUeNG1zMUVS3sXuLTkFB5YG8SgzdW1yXqlwrsG7L3ia1ozf7xnrFEB/a13VHnu7OgIcz2UaOMsLumxJ7X51DqCFN9NUD+xMqmEMzPdaAqWEpYksjFt/dSZwB1Ll4rGsYa1OJtY97RRbcxRe1jBFeyQygRlQsV+l9cLA5Z0QkVFkM2awYbNyTRO0vq48KmmSiezK4xD7ul7tZMZlTjbAHJKNNsnfmi8w50JYvzV/Nu1Ia4uOsSv/7yrRPN2XZbooSCLnZU7uY0xRD+jmvlgxDtZWPq/MB8+3GTdIvf+4e9ChACMZE2XJFAJc9eYgaWvBKNkWX5w2CiR7EGyVjkCMsImf4NwXTrZraL/LXskZ+j82Ihk0wF78BxqQ+nFyS7rFsDpkcW23Cdyr/CUHSPQgg9KXAV5yTjLmx40o8Hm1zD9+gifOgKf9zRxUHBtLUhG+Dm3GrIOo65x+XSWQrd1w1cp7G00zijOVyNPEIf684INgylH+Eb/aJbz6nbdU+4Py0L0siSf/ZO5mxViD24xrzUGozzU2wieb47Ae19v1JuVE3G31iF10egkaXjR95lPG62UaQ4L153mS+Fbrlgdkay5DE9Fj+BWggHIqokTQ9N5cRvsL19Ek2qkYUIt5QaAAb/YhemBCMNGt1ONFNzK2yuFWB
    username: AgBIe9QfrHPw6m0dMCZxnHxLCI+tg2SO04hb2HPho1BqYOSv3HCkeh0YBV4ZHsCWINRHAkqD2OZfztMNgspO8Y9sppQ9Od/3cNkLyaGpCxz7A+Ue0BR+c6sOjmsA+Chmzy6Su/bBU/0JIyCl9kdjbe5DJPY/WAN0I9CovPP2bhuQPl1bw7ixFjZQaOb5m0nZjAGSDtO/oP+qQC4QtVFpprwYOSNJ3Xm7yr0i9rpuFrC6hjefRaH+QjWELjzJz+ykn9Mvc1Anr6uDrvWOrkCI5oLE/axgBjGgNBolUH40y7Mran03BewpBGn4ooEQr/j1oKAhC0ox1kzxuFjv5zR75CiYcOhcDTJFepxa8Hrige/ef5cERQm/cEUN9fU07mPdM2Lt0x06OySd/mYVHF7Jk1lXQaWnL+zz9vMHfTuQ2F3Tj73Lk3gxgnS7xnpshs73TtDYmfJTFNbeI4irXpDVhSoYmaVz42spaYKPO6uJ5rvuu0stHTWi4hbL3wkPBVDoqMakKBbahbNpmapir2urFma5NseZO8PBGEwPxLMkfpFEN3jAf0LZLxNBfXcTy3X7DmRYKiLpUEb/TbZC7MNBSTQPVVEpCOTGQCZbwPAsK50n+BfXshwLLK/B8wbU9swSh9ofyls7KBZ9WRwmc2lykNemMHII19P+zPiTevDPCXF1VdVNsDitg1sE2g2pLptKdeXhVYpkrBz6
  template:
    metadata:
      annotations:
        jenkins.io/credentials-description: ghcr.io push token for proxmox-iac-landing
          (PX-017, packages-only scope)
      labels:
        jenkins.io/credentials-type: usernamePassword
      name: ghcr-push-token
      namespace: jenkins
