---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-push-token
  namespace: jenkins
spec:
  encryptedData:
    password: AgBN6HlBa+rPcmfE8yANuRGZY34HtO2Y66mDMmU6PBoA13PKAnBCT0/k/YxDmezY10n0/CbQrYvmKY94zSJxFuM//1Edg2iziNgtAMaE/V+8Py9OrtK2w9IdsM23wy69JaCGhcThXOCy5z36AY1uVfu7nkb+Dk1N65558XojQAfgoHFr/Qolv1bV282z0Z8TOgjkJ1CHVswyvoxgSR/eAsbvtOyvQlrhPWJRTNcHVedFnLZ9zAMcBmR0BmDf/OLyTlOYBqOmZ+byS2B4jaoebC3JTvk1YZEhdyXzcCN61GS97FY5L0Fvtx7ak7qnxGvqPSo/PcySBy0a6PoePfqdWAxdZFdP05jD3UZHE8B+7bVU/smz1Qe5neV2joLOd21QryrPWgIVPCSBYnUPB5ooGwcnSPouuN00fHKNeBHNfYqDosH1WA27Cz30MV1MLAe7PJgZWECSTzG5Aj6ApRMlNU3ksP2qdE8s2j+kGk0icCZrUhtbMry/VaoWlMIzwwhJdf6xhX6ktnCALH/Py8xfeKK3j95M/UgoEm6SKTuOGoR7urkrKPmyToJiN7DeDnOlUFdtN3MQMj/EH5EjVneiW87N/L6wMQ479j/nnp2e+yPCVhfR4u+lTzywiUKjAaNMXcHTesiHgFVCOzF80GHcbJke2i0rfQN2XUQ/oLLMXHyRfHwEi1+BgTDYgkRNhMZ/mLpzw1+W1lYXeeUVtsoBeno3hjUSKjqeAHK5na5WIL86VoPn7cnQQ/Py
    username: AgBe8smcHNX4RHBxRMk0EecunPoFLCqReVgQH6Vx6F04sLwQbAOP2pNL4FB0j28usiCOZcFRF31APnMjAFmdXi16Iu54iZjH23TYI5p/Pz5Ab8yJH3aWzx3Qz3EeUM4c+pZwrTC7ERjpvOyqxop5nZy4G9AP0bGkdWWSZrTibl8mXNglAZrzCUSZvyGMrUjM/0TJnT5tpEUocsUhK693VpOeVN0duPrAh5FXxiT69sl6GJXlDHYiN8HEFLQtH1+4iniY2ZzPlwgisS5YLObLZowWyIEh0f4ADl9sKDLd+icJhJVdTByguN4hpRUR7fOyVH1jnX72Il5GyUR3Avkpxu8+TiVZXSXJU0qvKs9iNeo1MQMQm8s+8Y6SrJdG8kN8Cf16Z3RjEVRuV3fqR7syFXZGu6sE6iObNEu4n9EM5hpB3C1lDufhQwjixboCPh0m1CFOFePSNBCsK0HxEMUUPWcAV8ujzEtxNxA9ATFAbu6RZmVhzcgSLntNqLE9TYwsaJQiCMY/UEJxmnyu9/RGBKL89dSv/3j5GcFzT0GyJYkPoOlAWBf0lq2dtxbCRnApk0RanU0TZMf49OQ4aXfj+ZjV/jYWV+6hkd/6+lxA0JvPv8xUw1xk6fuGSfhG1R468OffYQBtjKmJuLE7iNdwbYG7ASS/BxhmGO7Xsz/iU6bDebTPTLwFlvQGOIyP/kuvCFL4zCtkasiQ
  template:
    metadata:
      annotations:
        jenkins.io/credentials-description: ghcr.io push token for proxmox-iac-landing
          (PX-014)
      labels:
        jenkins.io/credentials-type: usernamePassword
      name: ghcr-push-token
      namespace: jenkins
