---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-auth
  namespace: minio
spec:
  encryptedData:
    rootPassword: AgCmhHFl+xCI+QnyUOl6RwoZytIBksEFB3xBQJXdDflcOyhWQeGi4OJPuGhiZpbm7sbRt9qlVf6eT6rzjvdSkR8YPQ9Q1tAftcw5I6ytZp4IR61ATqs2aNfRJt82GO6XFd+NdrhYA7pAIgD87+THPlD30ahH3sgVm+HyInWIbe80yBqb9m0gl9KeFYBy1SNaDxu9BecaLSAyqep/WX8if5+bSIJrBjZPU/s2FfgL0QGxWiceukUOywr/gujIQ0kHnIxv9fD0gfy3Zryn0IYshSbp4nsWfBR/RFYW1RHwg3O3JzqEek6g+IatriLQoW/OEEkuyrejmGuf9x8zzeLmb2BkAFx+lTaaSbDMQmevTJQVJSzFnlOOMxnKmGhHPjuS4iTo0vmlyipU+O0RJ6Hze7Kx6cYQNNHQYY2UAWvEn5OTJAuD0Q2qCl9doyfDHEaWca/LE+U7i8qDjtQ4E/DZTy60ZGf1mxZXQ47ZA9h7xYkZUCZL++P+Uk/a9Let+UlEjAkJSC5wVSqNv+Fsvp1aQOLmHtnEUZaJ0xpJqEOuFXOA/xhQDtxzYzNQbskqkyMXIb9BbCaWiLwQzqRrOJjvxY9aQJgLEbkeJspd+16iGEh1O7yhmta87JutzRLZXwXCillyQI3wQtCwsem8Af3YSQhvNc0+7BTYI4vr1wimhMUB/nMsqjb8ignyyHAtnyrYyyq1du8xmSEi5+R6vOGt1VJbcF6pKVPsHsVJXoSDIPGoP/pdD2wNY4GW
    rootUser: AgBEGuRasGZ1Hpz42Ol+ypAXU2NacjLfQPyLsVjfHFNNR69fezL3scrBu9PT/96eIDL8EtK6V/urnf6HSPwsVzyYc3cS7AQ0v8Ir+2zijZ/t4xIrCJ1sLtk2GOuQqpJi6yRPNIcuysU5RQkt1vFa/gVohbU/tN1Q5WfjljPZdRhBN1u0H4C4wRydTbtftePfPWITWB1JaO3Qw6BM+foYRxY+DVeJlbcTmDCjq2QyHYqpe0CVJ1mBR9+JdJHyDfnal8Aqox/HpN+xYJoyBMonGaHWjTu1wsQQZd5BznTE83MFs2bhtVpbncWWnqU3f4SglGnSyzblF7NW0Xsl5QdGYTAe4l33hhRYglaRWMvCbbcGOtQPgweUVjUPcQT590SRYVhpH/83VZjKuU2N9AqtGSzYLyZDn8k3arIeHtcBL7fGwQVwTtIpj3OHm6hgoKcLAn8M6Ku8GLYTqzmUdKqw6sojYs2dpxW1L8wCi0cY/vNvzzZ+OIR4wFwUOP0HEar0/RfLOXhJSNZXl/chBns7UFHRu5etWx/cjTk1J7VexPWmhxdnnA2Wisqj/mbeca/tEPcfo72a4I0uUx8Qi402nmACzNvHN3AC6Y3glbiv7h0mqbCkSl4OXxBpX1Qj4w98uEDZMHDs2y5F/zN/HlHHdWEHlisORbhJgq7Z+e8zdXvJcBneHWRI6FiBUR9teg6zMSYHEIJwQhURyPgyHqM=
  template:
    metadata:
      name: minio-auth
      namespace: minio
