---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-auth
  namespace: minio
spec:
  encryptedData:
    rootPassword: AgAqSfxKlqbM+BUH1742dBJFSnkUVl48ifuE57pBfyE3A/IXfaEwjSdtGjb/NFEBt8one5qiToyUoKtCteqRUJkkm3YfAUZzyyu+TE/vjupgugRVUATl8qEHUQt+Td/pzaO8c5ozKywtM+R/b040emk48yD7mDKg4DttVCVvZbdK4ZJ6irhhTRtrgcC/IBgiyDirsRU+3w++ODYs9Hd5NjON0GRoB1OfRyhLfGB4f/vVX3L7MOm7PkXPG/8hrYph0q1JmOeVBah1ebqGa/eEmoOHHXxZhJCbyUDttJcImaG1jvPf6JQ2I3aX7VAp9dP7mNJNmeSbdia7uqZiSYVX6+7yGUFOniCpe29b6nsS4D+3ArnMCI5YOFl1ef6dr0yPwbypcfMp9TO6REBdT51ECv8b46psIMf9OokHbCzlM+v3akVLTTGwcPo6NVjYwxEIsb9cFC0WC9q3v0fARkS7kO7LeEQyaNXEGxCSOGYitTXOjRf/Vwu+vsYVs/8o5m4CQ0t9V4nW5BoW1RJ+1fKx4REOB6ku3uJjomTyd4p639f8TBOeX0tKKiTdRunekJorzdV5oCCn2JdJWZmZwboR5x25G/xx2px12pbi4Gj07TDVwiUnQa4as4Z+WAHWg6wWJpN9eN3jD7ucdzpOWcaRLf6d7oLXLrrIBKRtHRMpEpNemPQKv9QJgE8mkU8ACRJT1We2ugWHXRb4FwmqBMAdu7IHniS0T+VtuJqkoIOgBp8=
    rootUser: AgA0Vn8d2nMrFIw04yShNhOIAaFNicUTveVjA2U5gDl2UHCi+6RgVMuuzJHbi7OlirMteovfvwX+EEHUjFCR62u7+eLMuvi1ALR+4/Tim52lJ6EAZAFBB7OkP3WpQUZnw76M84PQrZfBh0LKQ4LbFaIOf2i9XybJ5I6BMfyJ2gSGAP48JcVCuN4hJT9/u1XL6YOHy9Ool9uMrDdPJbo2turfzY4FiiZTfIrQXMNCV5jd63EgscGNINPmyI/kcr11kz0ZOGBpdQHZikoImB+iXi0KARBF5SQHAvC9iDMPNA9Wjw+sstr8sXM1H6mlSfMZ98DP+o8nTKJRs6fg1SQ3aXzOskTZ2dUE4Hl5KI0Bxi7eP3xH4Dgu9BMr6FiWpCOIoGsQ7J/NQAaHy87/go5GqW3lA/wpkW52QmRTBPdD1raqlHHkbpH8icyvZBAnRnF4zX5INLwFVLZWiNRl+97CdmYLaa0LmF94soloxY2wuSUetF0DQ0r3OGcW9NRQ5KK9ltGhsCS8KH303OXMdxrpRMa4prrmc4cRpDX3rXK3WDrJymD4LfdlMwNaEvPWAka0IZOI2wPskDDwm8hOkKnv+2K0ixVvGrjR/xXp5GQ6g2r/Fyk+0rX38q4zLjZ8ChIBJoYxXzUexA7k4Dn06VOevGcpm3N/VGHhm0u5APgxDYmY+nAYxOAxXKQRm6HAPM14vxiFZBz4O6dbdwTGPY8=
  template:
    metadata:
      name: minio-auth
      namespace: minio
