---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-auth
  namespace: minio
spec:
  encryptedData:
    root-password: AgAYF7/92y+zWM1NU83fNrIM6mO6YwselD6JfQKCuSSGWUi6gwGJgQE+v0YG1KMhjwIgbWDZhObn5ggFzpYe9w3QAsZ6nBUZMLSrh38vuJP5gSEvyWvOgmWMDZI3fw6TG8yNNGS4gSDc8re5M948ZVnfBszRWk3LZtjJ1z6M0RqFRjQoN23UobRlLgJaEssgkENxMnbEqfXkhUNqWVxOLul5KvT+cMdfkz0pAJXlcLvEzVd+jhcB6ZbL7HTegEBsdf6JqzgaNG13P3KruLIyhDarjmJmSVd03kmv5LrQvV2gDxc/N+W+H9Rbatfupqe5NVb4mBZCwD5Qit9eAmBUc/HGGTUpXQ2gtbJRCPp+XjusZ0DCpt5Wy31tM4DgBHhJ/JjdgiAQXGIzaC4f+nSfVPGM5pTnasUChAEcsy52Lt1uALTLuzOv/zM1NEZ/PMC/xX+QAfctJfQpzzsJufl1MkL9wSBbMt1S+AUdvVy9vKvzM5QH7QCLbLOED3sGmhnqfWfsd6q0FvZScypJfofhA+uqxefHWLxV48ccxsh6gxfVU+34aIfLexSZKtCdr0WcllCtLJw01KJgy2WsLol+rLRWwwVixH9Nk1bmMbVRqRWWSNX/jK1QUGYRGXs05CudDdVWJBHTvge1O/KXsFfpW7c+lWXggVFSfqGyFM00MFGjK7KHLPK9T72MSIu4tetMRQYfq45C8TNKMBhrpXTen6CLUv3/J+KSNY7Rqx1fJpk=
    root-user: AgB9HQUtpaRWZ/4LvEInG0QARrGeJJnZSSi6ggOnocoGPgqdT/pqEb1pZFh+HXrUa/Nzlh0DBMlZIc0sDgGMOPqx5GRu6H3WlKjw+YgQj8UHZBc5pQIKnnxPufSjvipQ0P9gw+sIrjhcZF5VI1dO/hEnsBrxmBtnof20Pm2BXVrpc+gaWbiPdsQfDXTd3xpFXh+rd33RAiMpx4RMBjBhNeR8NDJULr8bvX6BVN53LMvPGg7fhH2Ymf3SImDiHL0+JJXWdy4eOep0ZiKOOddLWwav+Q9HkSPSfghSg/YBEWNqUx9aPqI6uk4Hy1O3/75CuTzM/hgEvEESxrqFDTe2s/LLsDLoe2YNCQwRqETq7RxiHEHPv9gN32wyHDx+haUP5+egQw3CLCqskGIf4sxnXXLdoojb7EqYd9og9920FKS4lZRQ1KHo9LFMTH0q3w7ZmUm1WKJfF8Yj1CRrDyodukNj7Uf4N/zY+KvOVJ0ypoYI5Mpe3HetWb8CN24jGPtgaktHi6DEiRrRtCE8Q6oLJIRbd0U7u+sfBNpNbpfnNixbEM6jshKTAxyY4yduhvP1pcN2m/7kGRp5btVv7Zb6k2acFuNjT4POhuUra+MGrNwKXv7qQQdlbhCldYFEKmsIHZKafDnEZMUdp14umWkMTtkGk2RJxgMio62uTphFr5gP9FrKT0OuKnj/JhlIEuyJrC6PW+uSb07OI3KeY4w=
  template:
    metadata:
      name: minio-auth
      namespace: minio
