---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-backup-creds
  namespace: postgres
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgAodDZgvbppHhdqzC6I10/79dWEPECL/fdS0ZcE89WDGkHnvViVgRCqbKqvh2LTXN0WcgWrPozPESpR7agqmAAYhUm7hQwV4SLcSOkOjbis28thqgBDTLYoBNd5XrarWzvciLumki5IbAFEJ2EEG9L3GKtC3EbBjq2xTZqceebRpSXf6ZyOHh7jByxZdeRfpHly5ueMF7T0hqpc7JeMAST/GecKWnKGXT50/rQM/Mbfny/HhbWNk1FXxQtwMjK9DmOKd/PhvKTCgycyIWv5FY7OYMB2Y5EsAx/GH0oGH7lydZCMOXGv8sS53ahKNMjxhYfZO+6Ef1HOgtdGNPocJa+gKt4fqr4/spRY57eRYcW74wTvhZv/jXukjWRsOspUWMZoi0k/+ImudTi9cBu/HLo9D0why7fvVXG9GiSoMwgZ9sRVSVPmkA8hgB74FqHOoq4U4RmJkuGCjchtdu/mAEgYaIYN+TomThZsk1n0oR5NQoJoygzT+5qQJnzd+J9NnAXVMgMFxa4WwdCVQqSGbAD8Gn5Dh7ZqittR9FwKGaiOdjJaAm/9iokJdbzDkojCPJR7aFN4TClrYYH5eRghEj+7b1j7GeftiIJ9b/55dQUbWDnpi4Uk3KCso1H+r4TLznlkZRjnajjuGTg3zLQa7wqa+TeuYKItY0ERYnPXodRijPWvbMB3AmWzcDa//qvKErXVDKEzy/eExQwDA8E=
    AWS_SECRET_ACCESS_KEY: AgAoo2pNf2kusovP2Tr0Cn1IErQXnEPL+FBBLzY7sys9bs+pNzbfJxx5Y/P2VEQ+EaUCmGI9hqYeaLbrG0YOiQw9Oh4yqf/nXjQKwQ9rActiu3n7RMLL44CpyyvlRf60GGTdYWQ5EDWv02QAMzpQSXMrBFsv9HfwXjAyP3zJuF+Kr+5TROHwGyLFDGjk3SpFIdjwAhap11wKuIoruAa30kGlFpn+xWb87f1Fn9nXbUN2UrHIY2f2ltBIL2e+GeYxhfWAudQkKO8x57qgHDbguzvNy4U9pw/OGvRatXxbEadJqlCsL0JkRr65RD0YYthLXorO/IzhilolxyGEmW2FG7An++3y86Y6McvoQa5V0uRULVrEa9g9foNc0OH4nG3Swdbz7Iq7acEAMect4jNTkhO27IjceiA5fIzthJSeX+xFVtq2PZtgSiI3pwvDFSCK0SoHjP6NIkUx6Tr/V88m+KSLmrmJ/WCYts1H7SgVB7Y51Ki34u4H+4l8S/ObGbdkgbpfrP5NmRsfIRr0yJS8m2cjbAbr20W9AGVYvVkwE0cHYLQt0UzmZBL3fib27mGp1K9enoZ1yq57Qtn1IPn+jfaNKwN14YaOD3M6jed7DkNjwF9rUUHzHdUiJH9942wOAjUbAQe+s3h+4Pm9otsp5Q47wGdKfUe7zcndXXvvx9bUqJ15c12skix20BBgFQVZNvapWBRtXGov2dwq52wRFLu0V6dJR/114wpPC5BYx6bUhh2aXNbjYIl6
  template:
    metadata:
      name: postgres-backup-creds
      namespace: postgres
