---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-backup-creds
  namespace: postgres
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgCO0LgURq0uFebjsInJ76ckGMl4BF3CRj520c1ybjMHqDSpDqpq+m8pvfS9qmpdPm/gFjIlK8fs9Ru0U6kX2o1Y905RNmebFzqOowaFwsjUjdJjOh5hjHeSX8w4xoMCMR2m8GYWXKSkUF8LfNOMGQ51GIieDQfZVab8gEbqhfA/UKhKPO6pquYrHN0w5eQsPGDhPY0vQpK3kVd+sVDyhlWkAGOIvaXrL2iB+/ngDglkDqpkeQZJ9DbGVCUAJIFpvdo3uOdY2bV0FPPmzIun/E847A4t97dKrxJ36zVNgyGqn1PGSXwHArMIRGp+ZKblPmt144pZCAsaUeO8QN11/Sl0kn7ws7x+hofgBJcPbbVUZ46tRegnedmloUTj3L7gmCBGzhkZBPH58AoTCRaedd+dfuooxc5SdCUPEYAVOMBU0bILVVqCsQLxHNHmGkaM8FlB+rwjdZ6WXHtaVeAR0zN/QjcZtcAKV+RTmGm0PpVm4Z4YdLrha5/WbeBK+Kqba7ZwsUAxg+kKXh1/2Lh7MWRlCPsj/sCDDFSCjStlvwf4U4MgaJHa8YOpzSQ+EgcUDiVONceDBYiWAXBvfAmv74+0kHunKNk5GR5Lv16wwfl5u3RFE4b7rWsh6jFqvDB1ps01CeI/QguSrcESurk3QpWhcPViuIHxVNoJbVanoHWEI4ScaKeBVYugCIy3Cp1wswmiNEP4ja9nIYn5Asw=
    AWS_SECRET_ACCESS_KEY: AgCBG/FQ3HdRlydzVpXZGFU/e2r5on/9p4/SdBQ48qEFAb8UOIGGuodYP/hb5hupckREcWLRpNofyrgDX2UpgWB/ki/pAKnvD2kLsHuo4nS7uu4TjgbdgfYevatDBB0zrcQl/Yc8pODKEkSH1W8u/OF6ueI6iAOxi4JjXQeKQFvq9CdorSlsj3RkytwCtSGLLoXqz+Qb5VO7/YmqsXb0duJfLGOadIMTon4l55V5NY8OCeo1eldsinyGLG0U4eHiD2hpEm3nLJiAf9C7IvVUz2cfLIRK4JXjwRDQsrQISdU/mRD9wVE+MrmEp+/oYPFMy4Zo5AWg8Irp+59rcOI0vWg0l3hnfyitPOUn7OFp9gQEyB2hN8wbWs4jRZOSDsTkpxmGjs5EEejTk1YQg1Y56//2FmnnuaTiqvHPOrNvi4AuTqKRkG3Y+MP0Rk2ERbXNcc80jOkOv4tuPysI9GAkToXGF/plCVHp/oLzNiAkLjr6pB5XTQop1mvLU2E5PX+XAzKw2zCkD3C4Pj3rZ8w8AoCVIqlKUoIPpoPSjOUoF8+I9DEOVkddeNo3lCcEOsd03ZE3dFobN7PO+90uSiAec4PXvIrxAT5noi/xCgif8gsm0UEYRUev/gwYe5oj7HNjFan9IedZ9wc+O09RugJYDbHWba5IFkNmiXKEqp1tJv7M7loiJDdhsZYgey1Rmumr7stgb2po7Nm5RrqALW8uri1HF5IOmA8OcdeCBsrFOeI=
  template:
    metadata:
      name: postgres-backup-creds
      namespace: postgres
