---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBVUcroNNmFegWlLV6ky1W8Uu6kj/MQk+p5b87PxKSJWwRb+j0qLOQoCtWd6cVv1JQEgdPDCmNwOln7W066FPnwFQK1ovCNDBneCB6lGI/2RAlJsXaMcMfo/Rh0sqUjqDcPbZyfSluAtDoi2mOlX/IAs+mwSEDlGXTCCXlSy/4p3R17swR9rmEeHJz9uvpU2wflSv5g9tJKkvR9SJpPaZuehS8M1Lpvioagre6hHzmwN2Dnr5+sDNkUFGKRP9K3nEfDrJS/4My5UJssY1hYLrJ3XzR8Ue0wCgyajTWQHq+EfS2mQZBFaNG1HsHYLtwB3asSZtpCB4iVpMVt8WxwTY1K5/uy0rwYKdL7bXC9UW4olpNpedU02/0dft2X52bsK7lmnYstxUcVPI0HKMk6ghG6Nf+qQfR+d35QiikkTxkcbixc/s5oG4QIUbzNJ69urZZK/8Q/VJKtH6z6BHHXhBZdWecbf1+FD9MhU/jGblpOy3N2a8dbBKgsG2gOkHXky0rTZOpVbRT84qvWmTlERhLnen+IRxjRqm3PJcFUqYnzex7c7QJ7zBh/GA8BTVhQOq8PXKN0eipeuMf3BzUOnjXCZqZ5v7rn1QrJg6MVZ1KmoQORJOzAeIl3n/nxAQJjWaW5bxfkwigPh3W1XHDtETJXJYhAMunMXmDdRyNTh9bw3Ee6DsK1reD9yIWiV8FerBwYuj7Dwa59bVUsD7c3YmNPFwU7GuNgZVQ7qDmrFjwUHQ==
    admin-user: AgAekWr0p00jDR4Nx2VCpNGyR/qgaunKDGnEFHOzwvXidXYH4bNBWZlgkid6K9FizJfumk8hXWI76++tU0s2LKjxdM74seKJJtdqBgH3q7oHG53sipMaWNh2iGb8fP7kAqiGApsNTZ0mWOOD7F/fotnz8cnrWwLNknACpx1e6hAJaFrEio5w5Ds3ad2gTygOs+iHnG6LZ4BerRIQOqSkZTj3aLUdrclYqfsyucW1Z+C/m6eovPnNdiCbjBG2mmB16LtLAExC/f9hxtc/yfxeDyqgACN2wnNqszLaErdwlNVuEp6cWAq6SDX1fChC8yzrxf3oSi64vJdVuVshjxGElukKh7BoA9sg99qehxa8Y60ET/97sy5ruE7si0OKJIuu2RgyhoLUtt4eHC9o29GCfFO/3RW7CtMMTGs71PuxsCnqDPwIJu+0FcfdNOwCFOUbADrXF8/FWanHEmC3GDoGvFuVVoBRyxfsXo35BckyopcEKOUPBy7ppyvgBYdoAhOm/nBhqN6vMd5zgSJdF+pwBpQQQ1N4o8uRMmk2J5TsD76C8s9bXaVrs4IaQAKiVy2oB+ZVEkIwRVb/SWELK1W2I0BQjuYGxUkZsKih1milklt/k3XkD4WxmQmeVxP8Pg23EP55l8Qtk8kxMQjU0y306mkxlnSI0fHeMqg+6H+bbpFCixT2TxBrE4E7q37j1XUDIDlXniZKxA==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
