---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: landing-page
spec:
  encryptedData:
    .dockerconfigjson: AgClsXuciS+/UfTglTmhK0bmsjlAMLIeNquuq9PgguuauQ4ITnL/WiZeo7aYTpwCd8T6XxUZwspU4Pz92gJVxzvVDBYVznYsklZe7+Vm5HEK4MvRBN2ATTK1Bk4WZsrbcoYCZq/BJterOmAOQNrjbgUdM61zJyQtYidnQGLiRhfE4v1/8HUHhIASsU/HfMd/ngSVCRuuC8OdHNh68ya/0bncHeceF5pqAC0sO1v/sK/T09dEU0Oui+j0TckvkjwMNNSDA8KlRAhGOyttNejLBuS0qDlxa9x1pUqOdHy1ejNwjtmhM7qqFLwVEfwOewZ16gW/pnyQ++9EFNFwEVkKAt71QmEp0BVQXINOa5UXDCV45HhOQaMNTuqqXmQeNLd1mE+GZbgnSvxEBIjQZiWCignk8g9py8iYwePHUR7xHBMj/o+C342v5ViLq0Bpr2Rk6V56yQo4M9DIyXN1GPBi84R5wtf32Dy/BNN1DfuLXJx72RE+xFJRG1ucRMRvNJ9AJczP9Vy2Gd8rwrz2NRPsMqvWb2wGV7Cfhauac3/bt+cMRazh0pwV2XV0fky8GiL0oov1+i4n2/9945F3VGDf2wZX20dhaz9Di3AhQet+ot10lCoDaQ117FxrY9V36l1SPGOmcD8Abpf7RuH/u3u524uvQStsweYdlJyPxbu2o0O/AuWAS2W0JCvfLzVB7fKO4eLTYCxVz1XdeVb9Rvgp0G0Rxycj+Wg6oI0MN0Doi52UFI5yYp6MHMJDOwGQ5IoF/5tybdwqqMKCOB5Hs7i3A+aJrNtxaHiU5l07JfFSO54RCcPW+0g7y9JxpKB/sO7mfNUgKRphMH2m0JV3aY8VrbcqJuq3OlddXCtfrEL4Plh7IAQBjC++sDz21qGt97ucnJGVDtqFk1F5YixH1NXMPy27AAdjdHKfYY0s6iIX
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: landing-page
    type: kubernetes.io/dockerconfigjson
