---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: landing-page
spec:
  encryptedData:
    .dockerconfigjson: AgBo54uO6dDXRA0gqZ4hMVMIJ7MPP/oi5sXTDlRcFDg65gpnFh+EaSPCU+QsMw6J72IbVTl6XpHI/Xq8vTNqlAz4QYbq/uoT4dv9PtoxjEXobJz8H9j2VcL7VJnJe0yHxDi2D4uwd1m2NPdjORMKoUfvaI6gSQfGwGRKqkkiOhAupgtgV8sLSdhFuPXR9LTvIrbuq02OmmBVCcNEM7FXeE+tW4zUvxav2skjPMU7GGVCiZZsBwePWtx9/QsxOe7zhw+a7BssmWKxXOfbYOu2H+T2KrMBhtZM8rCZDHal+DhE0/Ot30Nj/YA8zID88hCgjzfMlvvXAtEmPLrp4Z5cBrV82DXYZf6r9Rc4gWDAuZTJTjj5j2KpcK/ShWa6cFww0xQQlf+WJl8IMICG9Hg05q6+LeC9DcG/QyQpONeTGhFqPLAJ1fu+/xvDA2PfD5Xg3ObzF9MzXw7IWqnY8uEWkllkKJI7/bscFX/s0nEp+GDE6tP7cU8j1UXK8Nw50/TpI1zGTkBuZz41p5RZL4uEwQgBgC5vNvGMsiKqnm+MfVU8oQhsIyYiwKNa+CwRxT92hKiPm3P460PKcSZC2kqyc0aVlJlX7/swRumebhI6SS1A1XfZ0fSarglvNzsdZNy1XNNImV8i4Z0ThWfmMjCKLjgCq5ZbHOVUrloI0ByXo5sViKFgOIaLWafJsT7Ayu8qycK8cTCZXEBQrl8Bt14zZMYJZys4SXFquF+TFg02d+6u1CcMCdufxhnaU+TgJj8ysNO2rYnb+yZxE1BaPZPldhZpssIk8roRcB8Yv2UJJx4/NMxc73OzK1L4HcpLZGU9vcs+2DJxXo75Hcx5fFRXhx5ULBMSGzDrYuQGo9xOvrK8aDguSz6GrRxzyrHiPIiOWRdkLYGHfCGg0zZ8tKYZEenJyga8UeQdMioLLOjn
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: landing-page
    type: kubernetes.io/dockerconfigjson
